### ISSUE TITLE
All benthic marine inverts?

### ISSUE THREAD

**Issue by aazaff** [lizmiller2633/molec-fossil-divrates#1]
At first, when we discussed it, I thought we should perhaps try to curate the molecular datasets to a certain set of target clades that are reasonably well-represented in the fossil record.

We can still do that, but it occurred to me that the hypothesis should not be clade-specific in any way. It makes more sense to actually collect as much molecular data for as many benthic groups as possible (crabs? echinoderms?) and not just target mollusks.

**Comment by lizmiller2633** [comment]
I agree- getting molecular data for lots of clades is not hard through timetree.org (although data vary a lot in quality). However we are still limited by the fossil record to some extent because we are making direct comparisons between data sources. It would be interesting to see if there is still concordance between groups with even a poor fossil record like some vertebrates

**Comment by aazaff** [comment]
[Mollusca_genus.nwk.zip](https://github.com/lizmiller2633/molec-fossil-divrates/files/3174347/Mollusca_genus.nwk.zip)
